# .github/PULL_REQUEST_TEMPLATE/pull_request.yml
name: "Pull request"
description: "Submit a change to Do Not Ghost Me"
title: "[PR] "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to **Do Not Ghost Me**! 🙌

        > **Note:** Opening an issue before submitting a PR is **required**.  
        > Please link it in the **Related issue(s)** section using `Closes #123`, `Fixes #123`, etc.

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: |
        Explain **what** this PR does in 2–3 sentences.

        - Focus on the user-facing impact (candidates, admins, self-hosters).
        - Mention the main area: report submission, rate limiting, top companies, admin panel, etc.
      placeholder: |
        This PR ...
        - ...
        - ...
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: "Related issue(s)"
      description: |
        Opening an issue before submitting a PR is **required**.

        Link the corresponding issue using one of the formats below:
        - `Closes #123`
        - `Fixes #123`
        - `Resolves #123`
        - `Related to #123`
      placeholder: |
        Closes #123
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: "Changes in detail"
      description: |
        List the key changes introduced by this PR.

        If you touched any of the following, please call it out explicitly:
        - Rate limiting / IP hashing
        - Prisma schema / migrations
        - Admin auth / sessions / cookies
        - Security-relevant code paths (validation, CSRF, logging, etc.)
      placeholder: |
        - [ ] ...
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: "Implementation notes"
      description: |
        Optional, but helpful:

        - Design decisions and trade-offs
        - Notable patterns or utilities introduced
        - Any deviations from existing conventions (and why)
      placeholder: |
        - ...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots / UI changes"
      description: |
        If this PR changes the UI, add before/after screenshots or short recordings.
      placeholder: |
        - Not applicable (no UI changes)
        - or: attach screenshots / links here
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Testing

        Describe **how** you tested this change.

        Locally, please prefer the project scripts:

        ```bash
        # Lint + typecheck
        npm run lint
        npm run check

        # Unit and integration tests (Vitest)
        npm run test
        # or during development
        npm run test:watch

        # Coverage (optional, but great for larger changes)
        npm run test:coverage

        # E2E tests (Playwright)
        npm run test:e2e
        ```

  - type: checkboxes
    id: tests-ran
    attributes:
      label: "What have you actually run for this PR?"
      description: "Select everything you have run locally for this change."
      options:
        - label: "`npm run lint`"
        - label: "`npm run check`"
        - label: "`npm run test`"
        - label: "`npm run test:coverage`"
        - label: "`npm run test:e2e`"
        - label: "`npm run verify`"
        - label: "Other (please describe in the Testing section above)"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Backwards compatibility / migration

  - type: checkboxes
    id: prisma-migration
    attributes:
      label: "Does this require a Prisma migration?"
      options:
        - label: "Yes (describe in the field below)"
        - label: "No"
    validations:
      required: false

  - type: checkboxes
    id: data-backfill
    attributes:
      label: "Does this require data backfill or manual admin steps?"
      options:
        - label: "Yes (describe in the field below)"
        - label: "No"
    validations:
      required: false

  - type: textarea
    id: migration-notes
    attributes:
      label: "Migration / manual steps notes"
      description: |
        If database-related, mention whether `prisma migrate dev` or `prisma migrate deploy` needs to be run after merging,
        and describe any required data backfill or admin steps.
      placeholder: |
        - Requires `prisma migrate dev` / `prisma migrate deploy`
        - Additional steps:
        - ...
    validations:
      required: false

  - type: textarea
    id: security-privacy
    attributes:
      label: "Security / privacy considerations"
      description: |
        Does this PR affect any of the following?

        - Rate limiting logic  
        - IP handling or logging  
        - Error logging / sensitive data  
        - Privacy guarantees described in `PRIVACY.md`

        If yes, explain briefly and confirm alignment with `PRIVACY.md`.
      placeholder: |
        - Impact:
        - Alignment with PRIVACY.md:
        - Additional notes:
    validations:
      required: false

  - type: textarea
    id: developer-experience
    attributes:
      label: "Developer experience"
      description: |
        For changes that affect local setup or DX:

        - Note if `README.md` needs or has received updates.
        - Mention if `scripts/dev/setup-db.sh` or `scripts/dev/seed-dummy-reports.js` behaviour is impacted.
      placeholder: |
        - README changes:
        - Dev scripts impact:
        - Other DX notes:
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please confirm the following before requesting review."
      options:
        - label: "PR scope is focused (no unrelated changes)."
        - label: "Code follows the existing style (TypeScript, strict checks, JSDoc where relevant)."
        - label: "New exported functions in `src/lib/**` or `src/app/**/_lib/**` include JSDoc."
        - label: "Tests and lints pass locally using the project scripts."
        - label: "Documentation (`README` / `PRIVACY` / comments) has been updated if behaviour changed."
    validations:
      required: false
